
```{r setup, include=FALSE, warning=FALSE}
library(broom)
library(lmerTest)
library(tidyverse)
```

# Analyze accuracy

## Accuracy by model and input type
```{r}
results <- read.csv("data/results_all.csv")
results$correct <- results$correct == "true" 

subj.acc <- results %>% group_by(split, model, training_type) %>% 
  summarise(acc=mean(correct))
```

```{r, fig.height=2.5, fig.width=3}
subj.acc %>% 
  mutate(model=recode(model, obj="Object-Aware HDP", trad="Traditional HDP"),
         training_type=factor(str_to_title(training_type), levels=c("Uniform", "Skewed"))) %>% 
ggplot(aes(x=training_type, y=acc)) +
  geom_line(aes(group=split), alpha=0.1) +
  geom_dotplot(aes(fill=training_type), binaxis = "y", alpha=0.3,
               stackdir = "center", dotsize = 0.9, show.legend = F) +
  stat_summary(geom = 'errorbar', fun.data=mean_se, linewidth=0.5,
               show.legend = F, width=0.2) +
  stat_summary(aes(fill=training_type), geom = 'pointrange', size=0.3,
               fun.data=mean_se, shape=23, show.legend = F) +
  facet_wrap(~ model) +
  theme_bw() + xlab("Input Type") + ylab("Test Accuracy") +
  theme(aspect.ratio = 1.5/1, text=element_text(size=8))
ggsave("figures/acc.png")
```

```{r}
acc.model.traintype.glmer <- 
  glmer(correct ~ model * training_type + (1|split) + (1|test_idx),
        data = results, family = "binomial")
summary(acc.model.traintype.glmer)

acc.model.traintype.lmer <- 
  lmer(acc ~ model * training_type + (1|split), data = subj.acc)
summary(acc.model.traintype.lmer)
```

# Visualize data points 

## Sample train/test split

### Ground truths
```{r}
ground_truths <- rbind(read.csv("data/category1.csv"), read.csv("data/category2.csv"))
ground_truths_categories <- data.frame(
  category_id = c(1,2), category_m0_x1 = c(-0.5,0.5), category_m0_x2 = c(-0.5,0.5) 
)
ground_truths_clusters <- ground_truths %>% 
  select(starts_with("cluster"), category_id) %>% distinct() %>% 
  mutate(category_m0_x1 = ifelse(category_id==1, -0.5, 0.5),
         category_m0_x2 = ifelse(category_id==1, -0.5, 0.5))
ground_truths_objects <- ground_truths %>% 
  select(starts_with("object"), cluster_mu_x1, cluster_mu_x2, 
         cluster_id, category_id) %>% distinct()

ground_truths.fig <- 
  ggplot(ground_truths, aes(x=percept_x1, y=percept_x2, color=as.factor(category_id))) + 
  geom_point(aes(shape="Perceptual Samples"), size=1, stroke=1, alpha=0.1) +
  geom_point(data=ground_truths_clusters, size=2, stroke=1, alpha=0.9, 
             aes(x=cluster_mu_x1, y=cluster_mu_x2, color=as.factor(category_id),
                 shape="Cluster Center")) +
  geom_segment(data=ground_truths_clusters,
    aes(x = cluster_mu_x1, y = cluster_mu_x2, 
        xend = category_m0_x1, yend = category_m0_x2),
        linewidth = 0.7, alpha = 0.8) +
  geom_point(data=ground_truths_objects, size=2, stroke=1, alpha=0.8,
             aes(x=object_phi_x1, y=object_phi_x2, color=as.factor(category_id),
                 shape="Object Center")) +
  geom_segment(data=ground_truths_objects,
    aes(x = object_phi_x1, y = object_phi_x2, 
        xend = cluster_mu_x1, yend = cluster_mu_x2),  
        linewidth = 0.3, alpha = 0.5) +
  geom_point(data=ground_truths_categories, size=2, stroke=1,
             aes(x=category_m0_x1, y=category_m0_x2,
                 shape="Category Center"), color="limegreen") +
  scale_color_manual(values = c("darkred", "darkblue"), name="Category") + 
  scale_shape_manual(
    name="Dot Type",  
    values=c("Category Center"=8, "Cluster Center"=19, 
             "Object Center"=1, "Perceptual Samples"=20)) + 
  theme_bw() + ggtitle("(a) Complete Dataset") +
  theme(aspect.ratio = 1/1.2, text=element_text(size=15)) + 
  xlab("x1") + ylab("x2") + xlim(-3, 6) + ylim(-2.1,3.7)
ground_truths.fig
```

### Uniform training
```{r}
uniform_training <- rbind(read.csv("data/sample_cat1_train_uniform.csv"),
                          read.csv("data/sample_cat2_train_uniform.csv"))
uniform_training_clusters <- uniform_training %>% 
  select(starts_with("cluster"), category_id) %>% distinct() %>% 
  mutate(category_m0_x1 = ifelse(category_id==1, -0.5, 0.5),
         category_m0_x2 = ifelse(category_id==1, -0.5, 0.5))
uniform_training_objects <- uniform_training %>% 
  select(starts_with("object"), cluster_mu_x1, cluster_mu_x2, 
         cluster_id, category_id) %>% distinct()

uniform_training.fig <- 
  ggplot(uniform_training, aes(x=percept_x1, y=percept_x2, color=as.factor(category_id))) + 
  geom_point(aes(shape="Perceptual Samples"), size=1, stroke=1, alpha=0.3) +
  geom_segment(aes(x = percept_x1, y = percept_x2,
                   xend = object_phi_x1, yend = object_phi_x2),
               linewidth = 0.2, alpha = 0.3) +
  geom_point(data=uniform_training_objects, size=2, stroke=1, alpha=0.8,
             aes(x=object_phi_x1, y=object_phi_x2, color=as.factor(category_id),
                 shape="Object Center")) +
  scale_color_manual(values = c("darkred", "darkblue"), name="Category") + 
  scale_shape_manual(
    name="Dot Type",  
    values=c("Category Center"=19, "Cluster Center"=16, 
             "Object Center"=1, "Perceptual Samples"=20)) + 
  theme_bw() + ggtitle("(b) Sample Uniform Input") +
  theme(aspect.ratio = 1/1.2, text=element_text(size=15)) + 
  xlab("x1") + ylab("x2") + xlim(-3, 6) + ylim(-2.1,3.7)
uniform_training.fig
```

### Skewed training
```{r}
skewed_training <- rbind(read.csv("data/sample_cat1_train_skewed.csv"),
                         read.csv("data/sample_cat2_train_skewed.csv"))
skewed_training_clusters <- skewed_training %>% 
  select(starts_with("cluster"), category_id) %>% distinct() %>% 
  mutate(category_m0_x1 = ifelse(category_id==1, -0.5, 0.5),
         category_m0_x2 = ifelse(category_id==1, -0.5, 0.5))
skewed_training_objects <- skewed_training %>% 
  select(starts_with("object"), cluster_mu_x1, cluster_mu_x2, 
         cluster_id, category_id) %>% distinct()

skewed_training.fig <- 
  ggplot(skewed_training, aes(x=percept_x1, y=percept_x2, color=as.factor(category_id))) + 
  geom_point(aes(shape="Perceptual Samples"), size=1, stroke=1, alpha=0.3) +
  geom_segment(aes(x = percept_x1, y = percept_x2,
                   xend = object_phi_x1, yend = object_phi_x2),
               linewidth = 0.2, alpha = 0.3) +
  geom_point(data=skewed_training_objects, size=2, stroke=1, alpha=0.8,
             aes(x=object_phi_x1, y=object_phi_x2, color=as.factor(category_id),
                 shape="Object Center")) +
  scale_color_manual(values = c("darkred", "darkblue"), name="Category") + 
  scale_shape_manual(
    name="Dot Type",  
    values=c("Category Center"=19, "Cluster Center"=16, 
             "Object Center"=1, "Perceptual Samples"=20)) + 
  theme_bw() + ggtitle("(c) Sample Skewed Input") +
  theme(aspect.ratio = 1/1.2, text=element_text(size=15)) + 
  xlab("x1") + ylab("x2") + xlim(-3, 6) + ylim(-2.1,3.7)

skewed_training.fig
```

## Test set
```{r}
test_set <- rbind(read.csv("data/sample_cat1_test.csv"),
                  read.csv("data/sample_cat2_test.csv"))
test_set_clusters <- test_set %>% 
  select(starts_with("cluster"), category_id) %>% distinct() %>% 
  mutate(category_m0_x1 = ifelse(category_id==1, -0.5, 0.5),
         category_m0_x2 = ifelse(category_id==1, -0.5, 0.5))
test_set_objects <- test_set %>% 
  select(starts_with("object"), cluster_mu_x1, cluster_mu_x2, 
         cluster_id, category_id) %>% distinct()

test_set.fig <- ggplot(test_set, aes(x=percept_x1, y=percept_x2, color=as.factor(category_id))) + 
  geom_point(aes(shape="Perceptual Samples"), size=1, stroke=1, alpha=0.3) +
  geom_segment(aes(x = percept_x1, y = percept_x2,
                   xend = object_phi_x1, yend = object_phi_x2),
               linewidth = 0.2, alpha = 0.3) +
  geom_point(data=test_set_objects, size=2, stroke=1, alpha=0.8,
             aes(x=object_phi_x1, y=object_phi_x2, color=as.factor(category_id),
                 shape="Object Center")) +
  scale_color_manual(values = c("darkred", "darkblue"), name="Category") + 
  scale_shape_manual(
    name="Dot Type",  
    values=c("Category Center"=19, "Cluster Center"=16, 
             "Object Center"=1, "Perceptual Samples"=20)) + 
  theme_bw() + ggtitle("(d) Sample Test Set") +
  theme(aspect.ratio = 1/1.2, text=element_text(size=15)) + 
  xlab("x1") + ylab("x2") + xlim(-3, 6) + ylim(-2.1,3.7)
test_set.fig
```

### Putting it together

```{r, fig.height=5, fig.width=5}
figs <- list(ground_truths.fig, uniform_training.fig, skewed_training.fig, test_set.fig)
figs <- lapply(figs, function(p) {
  p + theme(plot.title = element_text(size = 10), text=element_text(size=10)) +
    guides(shape=guide_legend(level=1, nrow=2, byrow=T),
           color=guide_legend(level=2, nrow=1, byrow=T)) +
    theme(
      legend.position      = "bottom",
      legend.box           = "vertical",
      legend.margin        = margin(0, 0, 1, 0),
      legend.title         = element_text(size = 10),
      legend.text         = element_text(size = 8),
      legend.key.height    = unit(0.3, "lines"),
      plot.margin = margin(0, 0, 3, 0)
    )
})

ggpubr::ggarrange(
  plotlist = figs, common.legend=T, nrow = 2, ncol=2,
  heights = c(1,1), legend = "bottom", align = "hv"
)
ggsave("figures/sample_train_test_splits.png")
```


## Test performance 
```{r, fig.height=3, fig.width=3}
results %>% filter(split==43) %>% 
  mutate(pred_cat=paste("Category",pred_cat),
         outcome = ifelse(correct, "Correct", "Incorrect")) %>% 
  mutate(model=recode(model, obj="Object-Aware HDP", trad="Traditional HDP"),
         training_type=factor(paste(str_to_title(training_type), "Input"), 
                              levels=c("Uniform Input", "Skewed Input"))) %>%
ggplot(aes(x=test_x1, y=test_x2, color=pred_cat)) + 
  geom_point(aes(shape=outcome, alpha=outcome), size=1, stroke=0.7) +
  scale_shape_manual(values = c(16, 4), name="Test Outcome") + 
  scale_alpha_manual(values = c(0.3, 1), name="Test Outcome") +
  scale_color_manual(values = c("darkred", "darkblue"), name="Predicted Category") + 
  facet_grid(model ~ training_type) + theme_bw() +
  xlab("x1") + ylab("x2") + xlim(-3, 6) + ylim(-2.1,3.7) +
  # guides(
  #   shape = guide_legend(order = 1, nrow = 2, byrow = TRUE),
  #   alpha = guide_legend(order = 1, nrow = 2, byrow = TRUE),
  #   color = guide_legend(order = 2, nrow = 2, byrow = TRUE)
  # ) +
  theme(aspect.ratio = 1/1.2, text=element_text(size=8), 
        legend.position = "bottom", legend.box = 'vertical',
        legend.margin = margin(-5,10,0,0), legend.title = element_text(size=7),
        legend.key.height = unit(0.3, "lines"), #legend.title.position = "top",
        legend.spacing.x = unit(20, "pt"))
ggsave("figures/point_predictions.png")
```

# Effects of within-category variance

## Accuracy by ground truth category
```{r, fig.height=3, fig.width=4}
sub.acc.truecat <- results %>% group_by(training_type, model, true_cat, split) %>% 
  summarise(acc=mean(correct)) 

sub.acc.truecat %>% 
  mutate(model=recode(model, obj="Object-Aware HDP", trad="Traditional HDP"),
         training_type=factor(paste(str_to_title(training_type), "Input"), 
                              levels=c("Uniform Input", "Skewed Input")),
         true_cat=paste("Category",true_cat)) %>% 
ggplot(aes(x=true_cat, y=acc)) +
  geom_dotplot(aes(fill=true_cat), binaxis = "y", alpha=0.3, 
               stackdir = "center", dotsize = 1.5, show.legend = F) +
  stat_summary(geom = 'errorbar', fun.data=mean_se, linewidth=0.5,
               show.legend = F, width=0.2) +
  stat_summary(aes(fill=true_cat), geom = 'pointrange', stroke=0.7,
               fun.data=mean_se, shape=23, show.legend = F) +
  facet_grid(model ~ training_type) + theme_bw() + 
  scale_fill_manual(values=c("gold", "violet")) +
  xlab("Ground Truth Category") + ylab("Test Accuracy") +
  theme(aspect.ratio = 1/1.3)
```

```{r}
sub.acc.truecat %>%
  group_by(model, training_type) %>%
  do(tidy(t.test(.$acc ~ .$true_cat)))
```


## Novelty preference
```{r, fig.height=3, fig.width=4}
novel_pref_scores <- rbind(
  results %>% 
    mutate(true_cat = paste0("cat", true_cat), 
           p_cat1=exp(logp_cat1)) %>% 
    group_by(split, true_cat, model, training_type) %>% 
    summarise(mean_p_cat1 = mean(p_cat1)) %>% 
    pivot_wider(values_from = mean_p_cat1, names_from = true_cat) %>% 
    mutate(novel_pref_score = cat1-cat2) %>% 
    mutate(train_cat = "Category 1"),
  results %>% 
    mutate(true_cat = paste0("cat", true_cat), 
           p_cat2=exp(logp_cat2)) %>% 
    group_by(split, true_cat, model, training_type) %>% 
    summarise(mean_p_cat2 = mean(p_cat2)) %>% 
    pivot_wider(values_from = mean_p_cat2, names_from = true_cat) %>% 
    mutate(novel_pref_score = cat2-cat1) %>% 
    mutate(train_cat = "Category 2")
) %>% 
  mutate(model=recode(model, obj="Object-Aware HDP", trad="Traditional HDP"),
         training_type=factor(paste(str_to_title(training_type), "Input"), 
                              levels=c("Uniform Input", "Skewed Input"))) 

ggplot(novel_pref_scores, aes(x=train_cat, y=novel_pref_score)) +
  geom_hline(yintercept = 0, linetype=2) + 
  geom_dotplot(aes(fill=train_cat), binaxis = "y", alpha=0.3,
               stackdir = "center", dotsize = 1.5, show.legend = F) +
  stat_summary(geom = 'errorbar', fun.data=mean_se, linewidth=0.5,
               show.legend = F, width=0.2) +
  stat_summary(aes(fill=train_cat), geom = 'pointrange', stroke=0.7,
               fun.data=mean_se, shape=23, show.legend = F) +
  facet_grid(model ~ training_type) + theme_bw() + 
  scale_fill_manual(values=c("gold", "violet")) +
  xlab("Input Category") + ylab("Preference for Novel Category") +
  theme(aspect.ratio = 1/1.3)
ggsave("figures/pref_novel_category.png")
```

```{r}
novel_pref_scores %>%
  group_by(train_cat, training_type, model) %>%
  do(tidy(wilcox.test(.$novel_pref_score, mu = 0, exact = FALSE, 
                      alternative = "greater")))

novel_pref_scores %>% mutate(train_cat=as.factor(train_cat)) %>% 
  group_by(training_type, model) %>%
  do(tidy(wilcox.test(.$novel_pref_score ~ .$train_cat, exact = FALSE)))
```

